apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`assistant.mauzlab.de`)
      services:
        - name: home-assistant
          port: 8123
  tls: {}