apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: MauzLab
    background: 
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: xl          
      saturate: 50     
      brightness: 25   
      opacity: 40

    layout:
      Core:
        header: true
        style: row
        columns: 2
      Apps:
        header: true
        style: row
        columns: 2

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Repo:
            - icon: github.png
              href: https://github.com/jdamp/homelab
  services.yaml: |
    - Core:
        - NAS:
            href: http://dxp-2800
            icon: ugreen-nas.png
            description: UGREEN NAS
        - FritzBox:
            href: https://fritz.box/
            icon: fritzbox.png
            description: Fritz!Box Webinterface
        - ArgoCD:
            href: https://argocd.mauzlab.de
            icon: argo-cd.png
            description: GitOps Deployments
        - Grafana:
            href: https://grafana.mauzlab.de
            icon: grafana.png
            description: Monitoring & Dashboards
    - Apps:
        - Vaultwarden:
            href: https://passwort.mauzlab.de
            icon: vaultwarden.png
            description: Password Manager
        - Paperless-ngx:
            href: https://akten.mauzlab.de
            icon: paperless-ngx.png
            description: Document Management
        - Mealie:
            href: https://futter.mauzlab.de
            icon: mealie.png
            description: Recipe Manager
        - HortusFox:
            href: https://kratzbaum.mauzlab.de
            icon: hortusfox.png
            description: Plant Management
        - Jellyfin:
            href: https://kino.mauzlab.de
            icon: jellyfin.png
            description: Media Server
        - Immich:
            href: https://fotos.mauzlab.de
            icon: immich.png
            description: Photo Library
        - Linkding:
            href: https://links.mauzlab.de
            icon: linkding.png
            description: Links
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""