apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hortusfox-app-pvc
  labels:
    app: hortusfox
spec:
  storageClassName: nfs-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
