apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hortusfox-ingress
  namespace: hortusfox
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plants.lab.home`)
      services:
        - name: hortusfox-service
          port: 80
  tls: {}
