apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hortusfox

resources:
  - mariadb-volume.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - app-pvc.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml
  - sealed-secrets.yaml
