apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hortusfox

resources:
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - app-pvc.yaml
  - app-deployment.yaml
  - app-service.yaml
  - secrets.yaml
