apiVersion: v1
kind: Secret
metadata:
  name: hortusfox-secrets
  namespace: hortusfox
type: Opaque
stringData:
  admin-email: "admin@example.com"
  admin-password: "password"
  mariadb-root-password: "my-secret-pw"
  mariadb-password: "password"
