# CloudNativePG operator installation
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.28/releases/cnpg-1.28.0.yaml

# Issue with ArgoCD and CloudNativePG CRD poolers.postgresql.cnpg.io, see https://github.com/cloudnative-pg/charts/issues/325
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
