apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-ingress
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`passwort.mauzlab.de`)
      services:
        - name: vaultwarden-service
          port: 80
  tls: {}
