apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - ../../base/postgres-cluster
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml

patches:
  - path: postgres-patches.yaml
