# Patches to customize the postgres-cluster base for vaultwarden
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nas-s3-store
spec:
  configuration:
    destinationPath: s3://backups/vaultwarden/
