apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-pvc
  labels:
    app: vaultwarden
spec:
  storageClassName: nfs-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi