---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-s3-secrets
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgAPI2R7GkZNpa2Ap7GATlBqXBIW5k8kgvf8pBrovg4NsGKp+5j9nN4DGEtQNfqqA22/MZaKRFuKg3d3uSr8jqoktQtkhRdmE0A1binx4qISpq6rec5nZSuSWAA3my3ruIjyzCNlFE+5s5zwmg5GBnNZ5DJSF4q+dvrDzB63B/CqF2cwYlZaRRt7fn1x2UL7AtxlM/VCchsPOsP4POapxfo2xdrIO5lfVQ7+F9PbkVEKCnNF2zzHU2mQcmrD6dHWq5c8+9xFiAgZGaTec3p2swsLB+qlVtnB7mvNF7I7xnEttUdutkXPy6dhaC4rp62K5avFj/NF1Jq7Qi4OEjyrzw+OYbTt987FpWxV47g6wDDPOym68IJfnvRMsOf3Mv1nC5TPAo5egjieqB2A/tj17JCjhmVEZfsYNhuSi+eCckSuQJbeTOJLAi3Yv5a1jwfSSNXfT2oF2Pz1ZC1DQihNf7gBWw677lHLtk7teBoXuPwtEffrqXTXWelUQObWA0uDyAglmeS/FIjE2213wuZUnPeDseIJ/DMN8rOBUVa4MD0rDGP44YZvHPui7f27nea8vFfCQLbU9t9LrstNqYsmnjiR0DesRf8Lh0oXgRMWld01b8gmT8+tdLWN/R7qFNWITzTy6zP+BiAk6hdcUCNJ9pAR0J33D9EsnPfU4Eyv92Dgb2Y8FszxYzZaBIR3Rvo8u9PzGLIl+FbTOiEIDrnUlij/k8csiwGheME=
    S3_ACCESS_SECRET_KEY: AgCmfj+gXNHzxEUGjTQ/dNWsOPA7friUyxS9NcO2UpK3Hvz2AP3gUxz3OLZajWPHVFrciLdZKYGkeuNzbpO/35O1seC7kL+t/BnWpf99hNQENb8iroSOTtJAvzfZ0B2pfkXVvDnsaDLLuyQnPab9tur/nJPgKmsZ/looOfM6fZ5XZp7KMNlKCiN8i2oA2AFMF/0p3SteU79lYRWRJq4Q8SqEE9uXC74WruwoLhiAzjBeC+wH13emKac4iXLsF0sTOyeR1AFi7pkyQ/pq/5OsQ46k22wGdN1UlVkDP6t0CQgoYLXExzLIR7IlPcspyTeflIAOS0zQdtLsTTkQ9OCZ5kuNu9fCBQp6FirRJODfwLPO5iF05RJufhFRq9n3jnSekpy58s9nuGkwf2SwqGn9bbJZnRzJJWxsoAHKB3D11SMilna+SpwsPvgXuZkskewubxd+TL/YtXoBstNRO0KyNNlxaca9c3FocXKVaXPozv5GQr6YhUu3DONQ1EGIdn/b7bXMzruRT7BRkMCyo7XGk1yKCFkBTte/5w7qmcHXDWzS3P9dT7jvzk3etmXeCeeCLHlSve8DdXh8ukkn6owDyX4vXbuUljh6RKekFUU3ZX0FWWcTUShxRka/smVWgueAMI05R3ibMyzOzhuzyP/B/Fe5+ORwM1InHR9SC2pqcf4SM9ijAfAOkbnIHIwkxgkNd2P1ZC9qZNpGFTH1fLxQfIJHa0dVcanVdK8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-s3-secrets
    type: Opaque
