apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smoke-test
  namespace: default
spec:
  encryptedData:
    foo: AgB7SafHKvVRJnM47pKdciKWN+M/zLsJBE1EnnM8d9pBUedA8xIOyCiR8EFGI5iFU3P0Y1+yv0vd2tlGBtr0kOglOJP9fh0AWnfZEU8YKb554KsiexAUbXOGp5Wc3A+t8qLnm+Ek5h4uj9IKKCIjOzOrQpfHhY5IDSAE/lBbXokSdHN/ohkP3sXo/I4GhXAChUmKhn6Hxos4xKCKfgD7tP/1us54nbQRxTWnSulo47Ir+ot3wc17KV1ZngzWptEPB/1HDi2kJd59tdAzjQWPsC/ZYfAFKc7q+T5gegFTtMKDjaVBt4dMqNdcCHMQzbHJMHogUF4d+Tz7foP22C8zMRIqYsG9UmitptOdyJDhJ51w8BTPj+2UlwFrw9ZQbHnnDLDxQL1FJpF997Biy3mSR0mXZq+UOSl/6VqYqVEsAp3XrKwOALFG4eUPBfoovWufdHqG3WyPyZWqMNkyqoM6sWtjP6U3EyyegQuc4aZuPZ0hEcjmdOkKnf6kE93BrwTJIedLp8z//1s8rup1CCkeKVaFr/JF+wPI82CrnaWK6j40Z87Ae/MlNFyWP0RKdEYKRBqtEsDLxc1kssrSnuP6MX5638UAGPOJsMngWmcq6r9/rBM2AcihqlANzRQ3STrnWjwhDmVYCAqXSQFiaj21hWB7C7SkiD/UGhkEf8Xh4WkxckynZXjvmafWUKtL2ugUiRyADVs=
  template:
    metadata:
      name: smoke-test
      namespace: default
