apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-weekly-backup
spec:
  # Format: Sec Min Hour Day Month DayOfWeek
  schedule: "0 0 3 * * 0"
  cluster:
    name: immich-database
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
