apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless-ngx

resources:
  - ../../base/postgres-cluster
  # Redis
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  # Paperless
  - paperless/deployment.yaml
  - paperless/service.yaml
  - paperless/pvc.yaml
  - paperless/ingress.yaml
  - paperless/sealed-secrets.yaml

patches:
  - path: postgres/patches.yaml
