apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless-ngx

resources:
  # Postgres secrets
  - postgres/postgres-sealed-secrets.yaml
  # Redis
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  # Paperless
  - paperless/deployment.yaml
  - paperless/service.yaml
  - paperless/pvc.yaml
  - paperless/ingress.yaml
  - paperless/sealed-secrets.yaml

