apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-ingress
  namespace: vikunja
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`todo.mauzlab.de`)
      services:
        - name: vikunja-vikunja
          port: 3456
  tls: {}
