apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

# Helm chart for Vikunja
helmCharts:
  - name: vikunja
    repo: oci://ghcr.io/go-vikunja/helm-chart
    version: 2.0.0
    releaseName: vikunja
    valuesFile: vikunja-values.yaml

resources:
  - ../../base/postgres-cluster
  - ingress.yaml

patches:
  - path: postgres-patches.yaml
