apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

# Helm chart for Vikunja
helmCharts:
  - name: vikunja
    repo: oci://ghcr.io/go-vikunja/helm-chart
    version: 2.0.0
    releaseName: vikunja
    valuesFile: vikunja-values.yaml

resources:
  - postgres/sealed-secrets.yaml
  - ingress.yaml

patches:
  # Fix ConfigMap name mismatch - chart hardcodes volume ref as vikunja-vikunja-config
  - target:
      kind: ConfigMap
      name: vikunja-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: vikunja-vikunja-config
