---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-s3-secrets
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgBghcYj5x0di6y4srEsSWgX1jxWmwv6mHsUXYkKIbOPZEX3hs2zhO1hvlEYDWkVYqcxknGU36c+Qk48UAKsuYpYo3w4k7GLCCndnZGbHKzvzuQCT8YftANya00WhAH1H8ouNzTXqsVd8oKOXaecwAOwUqI/lali8WciWzjAuCrjtvPgQU6Mc9Y57O2wQ89KDUwdDDPLe6EFT+sayGPbuZTCsoRPI39xbM87o6LmbFCVp7AflhWZeX+6SA625a7J6B9PikNUD0tMSanZseWPtRUbCI2jUPBpkgPmSwXEcEQEGysprAm3nC2hiR86/Ds0fQrozvlazqvSbnuWOCqG9sQCcVqVE6dEvIvSHM0cp4JnkmM0I7v+Y+Qyk45dA6xSYMISwAjBE1+dQ6/gr1Zu+MP7kXyq5o/IP3GNnJDjEj3iEx3J+Vem+lt8J2V/aWxWEdrwTrbRN2KcGKfti6fGFZwM3TQ/Z4CXpqWGhxqEY/OLxVyjjMSLZBsZGU7uOmWNI0zlFiJepgYpc9HfL96WsN2azQFHuaw87c9I6naYiYxBAYFBEbUlnTvsyR12XiVJSUbeT4dksAB1rSFvjtmZLb5yplz6R+6AU2V0YsPrc0400NuFE4A2yRJbySKvNgkHUGKp4xVv+G1GNn/y6da+1kHV2eEW6te29qWDBT4KzSP/XuZF++f47rH7QLkua7evVo25spLYniP0ngxMbKTotGiyblvjWrquWa0=
    S3_ACCESS_SECRET_KEY: AgCDfccAYDFfXDwAnibSEKS34NSPpLA6YWoMO0MAyyMyjVwNYGGlNvQPhLxCZ/zH/jO4nAG56LJvjHcrkGyj6NYMjaukFw1NMG1zU46f+9/DkKVUndXXMmI9z5IApvIh7VbL73XgALyyYn0ZirmhHautpk5AROG/ItHaEa9eAWDWoTbqaziOgevoWXh2bTxybrfz6YHDD6E9vcduJSufaLylATaBSTulRN0X0loOK32/6sZwRJ8x9zKH9h24Sh54dYf+VT30hRIjAGU+u2s74qf1s1mWTy1mVzW/9Mec5TK/gmhRUZGAEBfNA6KpLQOdBHIbarMDrPvgzm6KMvACToLdg9hEM6DmntFIvB7hDuEtcfsdMGqi2ewljY9/JVEgRlQx8FDL0cdc9Hs9/gpCm4uBtkcJuF4oXNWQiDYb1t8WKkwFQUtcnZWNvzoU9JQa9nwCzWmLNowaca2saKsubRfyT482VjCqVCw+96mlN7eub4o9BGyOyxhPDW6hBP5zdaBgS2D1nVG9ylyDqrbQbjEM74hKWqeLsmifQYpRxWfT1ppFQ2yUlcgyNjrrkXVrcV0SFR0MKmiPyErp2VTJPNTL0CLN/Vmg1xShJmbAz6lg2bcyc29vSclfon0OQeHvQp34TRF8VbF210+qzPuk+gLnVUlUBxYpP1I//QDulp+tyHZTBAS1CNQhv5DFhPizfULd34wb59TsfXhGkd9JeHjuv1eI5tU8XTA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-s3-secrets
    type: Opaque
