apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`adguard.mauzlab.de`)
      services:
        - name: adguard-web
          port: 80
  tls: {}
