apiVersion: v2
name: jellyfin
description: A wrapper chart for jellyfin/jellyfin-helm
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: jellyfin
    version: 3.0.0
    repository: https://jellyfin.github.io/jellyfin-helm