apiVersion: v2
name: monitoring
description: A wrapper chart for the VictoriaMetrics Stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.66.1
    repository: https://victoriametrics.github.io/helm-charts/
