k3s_install_script_url: https://get.k3s.io/
k3s_install_script_path: /usr/local/bin/k3s-install.sh

k3s_binary_path: /usr/local/bin/k3s
k3s_server_token_path: /var/lib/rancher/k3s/server/token

k3s_disable_servicelb: true

# Taints to apply to control-plane nodes to prevent scheduling workloads.
# Example: ["node-role.kubernetes.io/control-plane=true:NoSchedule"]
k3s_control_plane_taints:
	- node-role.kubernetes.io/control-plane=true:NoSchedule

k3s_install_timeout: 120
k3s_api_port: 6443
k3s_api_wait_timeout: 300
