apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie-ingress
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`futter.mauzlab.de`)
      services:
        - name: mealie-service
          port: 80
  tls: {}