apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mealie

resources:
  - mealie-volume.yaml
  - sealed-secrets.yaml
  - postgres-sealed-secrets.yaml
  - mealie-deployment.yaml
  - mealie-service.yaml
  - mealie-ingress.yaml
