apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mealie

resources:
  - ../../base/postgres-cluster
  - mealie-volume.yaml
  - mealie-deployment.yaml
  - mealie-service.yaml
  - mealie-ingress.yaml

patches:
  - path: postgres-patches.yaml
