apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.0.60:3260
    iqn: iqn.2025-03.com.ugreen:mealie
    lun: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mealie-pv
  storageClassName: ""
