---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCds88Ex/QkU7IOuEAWXlIzXox/Abfl+wpwoD0Ii1UndSlOLov6uoOmBKZa4PJJySegeXQsLHYWRen0EDJiyV0Uszzk8bbjT6+MOlUKyDkLhdowdLZIDNa8rerzBk5ZYZ7oOtgtxVnhylr5yNWwXIHV7vEklFmAFqLi7k/6PhyrRRH48cYC1YODikSYgQGxtOTRCniCaxqUSDVWisz94KDRR4bqPYtYJipSIaQgbTNzdQymOp35YYkemLyxXn5izdFzkpYI4Md0E5FZX7KoIOH3r0OkvJIv4tbauC3DKvpRf5UOD8DYjReOVLinQaVrMeTBjoFk7f7Wa8Bi3lnA+omVWEThmMFvQ5SyxKAt3aOIO2GeBJDqXFn+0TpDFiS2qoQNZR9iYG0rMSKgwTFnsrY7KxK/oJrEKN+vENzSeopLBYpdfq2PN4a5p5iCYm1zYNL6nWP69M+Oxjn9F5UdDWB8UMSJa6MPLbL2dfNFQ0VBeDfv4qm5MkGLX6Iou52tBVsxQh1507jGbnYIWPmsyguuutreA2tTld73mcxVdRb4HBqRO1slUkm3LD7fkDIlToW9DUaoNk4TlT2/hORt3Uf3A4/owwIlB+snNCS5y299Cp4uN3NzIvlKHO2hQ2NY3y2cgnZlj3H/SZJvlHCLSr6a5Miw9G/jQ37R2bUhDI5ko+0j8uUb/Y+Fbj/VXSGhr0ENSaMnJbDwp6RohA/lhwirHPQiooTCL9Y=
    S3_ACCESS_SECRET_KEY: AgC5BSKpehS38G2I1lW7v6L6pORnhdu8GfkLEeWiJmr1eHwbNR5cp7SkCP5DeaTcFQomitGq4wxqH3WLXwQC0HbnEqsrGUOpsdLifaVZN1xXMc6Whg8jHBHi+EBAQdXCwAnckdi2f44OWdZ9jjFeLaLXnuJuM3ArNx5CGbu3fw8o21L4wsWi8Z1uPz6Q/mOj6JJEVoOL+Ot3jsvbh4xH75WG28W13HILCG/PzrhYSWEbdAS1umbzf7YdzSTan1cXI3GDcDf5z3FTxF4yTF6kHOAhRB/f8/YypU6l8QTNc/W3lpiP2hwLrApsuhcX+5KifE2dKKxNZz/fXOOK7dNfs3TCyOhNaq6DgSn6HkxaoYuroK12yuZk1/lqYRW5OValubLMgNGRf0006vJ5LPd39dMnD+NOZD1YyUD7vO5QAofnpQRPT73adCd10kpPSWOVC87xDi6/GNqFiac1vdG8RaM82T21V6qscXKiUXGXbKG7rUnWK5na1hJfQqtERZTf9JjTU/VST3z2+a3+iBY6Iv09c5IuKiG3vDN5gR5anXlhuVYwFBGqjmkf2YWXoEdTMt783xzYCex/5UnElowfdPiTorP+RNg3OOJVxHhySiaKanQjdJM4GxZ+TMw5SV7Rl4T13m5T9Qj9zScx8N68fEhNvK6lMlwXz+02ejWDcDWnhIXqnfJ/Of2h5ACYQGEc4tpKqL2jtHKz5p6uhGYS6nzM0FBfiTEOdn8=
  template:
    metadata:
      name: mealie-secrets
      namespace: mealie
    type: Opaque
