---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCZlyAsfZ+fCIGUL20Ob2Aflnq88epvGfG/j72ah92DBoF4VfYmaGrH6gB98yu00d7pnt01WdCBOEK/KlXAJ2IquyisVEoPFo+iqnmsMr8IewtFlzfgKPC2+8IwiPNaHNKIe5xCtWFKNVVSpKe0g+KeehP1hyByUfWv34nk8eDFdnLdd1RpnGZirRlm/k4QuuUSYyQQDvLZWnAzS/0eycVYisO9GBR4xTa1FOGG41fPYkvRH0S30zKTnS77YQbBLBEbLtb+Ey+7jX37BPmEAIAbeZJ/MZdFfffVojA16r2467ELZN/X12p1SCLM3WyIKxCa5pp4/vIO+FpkZUnXUkvUF0qZSYb33/o/y68fRqyZwaL7dwCLX90BO8NDaLBW3oJQThmiDfe2chF217YGkeOUVCALQLEJEv59N1yvnGgD31j0tyN5IdqHfFT6mre7/SgFzOv2I4V0gHWvO1kFOX8wXvlCdNaL0SvJQgJR8cEBDaFAIvmbpeC94+bVquYlmQ2sh9DcCpegPKVQaIgN7FwIhhLt2Wk4Va+x62UrGVjFY97iOtFSTvBdkPopIAt2mJPVsicdkjnzBb2WPMyYRFeKU95fZlx+GdoHEIcdHZu+DK9N8RnNGGj/XbvSvqR0TogKWjVoUvRWfFqVvcHtsJBS6hZJ0TJH57SZhz2Lks7H1uAm1shlJgC2TuYifWuI9z6XROk3EEh81/8TYkl75nJE/i7KfHUvjIQ=
    S3_ACCESS_SECRET_KEY: AgCMxzXikTb4r5U+Hlq0+fbzhdjvG4UorK535q6ZhewGKCe3yzEKSFnmc1iomWDnsLntbbOEBZR5azsJ08nBulRP+nsuy+DYdgzEljB2+iNNswR1xnnqxwrMG4uxrapMmZcWgXlLySITFdN3oQ5F0gfZqjh8WDHr93niVXLAcv3TQNlYyZ2nr15k4bpjHIVHvAqwuEkirDaRUaI6uagApwrrhAYh8EyWvfZf8jTp6O8dTt5kLJlfhnmAgwHksIqYfcgcHldmNezrB5vgc7EFwYIKfybp1KIyXnR7YWymDDgmNbsrnZq5bksrkJebshboSP7G6W7yD48i9z8tkFIw04T4rnWsHmC4/a5nTFlrVfR89lUcXhQlM56J+QLfIj/QyAf5ep3KSOC/a5t0cCUAPMGGwE9hrTK9EeZNIsjldBJI27Py34L3btTPdozRXANeZASJ8rcMo2xXga84ESjAQiWioIY1WC6OM+unCz2XaphfbbtWQh78GE+NUrsfj6GZgnfXMn5RpB30nURKq93CVnfUGRCzyvfur5nSEoFrsppoIjACZ3G8/c4w++z0++Gw1T8Js05Rwb5iJLe649Z7asW6P+xmx7Q/hcS48yD6JROmeulfyaXQurxd0MyQvb4tuCobl0D3F+QBrb+X5D1eNf165vwvlhj7U28TatZ8vy8PLthJNzJ5v8JqujDyNK12UOS4CCs9QoffeVZu0HTIl8xjLlDPFrUycec=
  template:
    metadata:
      name: mealie-secrets
      namespace: mealie
    type: Opaque
