apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - cert-manager-sealed-secret.yaml

helmCharts:
- name: cert-manager
  repo: oci://quay.io/jetstack/charts
  version: v1.19.2
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml
  includeCRDs: true
