apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding

resources:
  - pvc.yaml
  - sealed-secrets.yaml
  - postgres-cluster-app-sealed-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
