apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding

resources:
  - ../../base/postgres-cluster
  - pvc.yaml
  - sealed-secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

patches:
  - path: postgres-patches.yaml
