---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgB1lRR/0CXtQq4OJrgnsMtSOWFfhIxO8bgbXlV0f7kCmmxKtPbFblmCv70VtrMU5VWD2mhnTINGP3AnRBVgQP8S4VmHP9nP517RQH18yurILVZeFAqPUURK4gb2ud7Lw4aAliU4v8exitbvDeFVOyjmTsadg9IAr3DqgGtqXyGsssgs5h94jUMQbrFuC+IM6WbAoS/1V88eCjcjzYRiTKE6MBNKpiWuL8oO7izW0l4HbfOvYUjUnj8mpAuDv7mO5QMAliuFOAQNPSZ6IGwFiK/DdAW8tS9Z3GhjdaRp39gzDEGBzGwmGP6UNDNttYcfPpeSnQCH4A/K9adDpD26P/dn4sFDCenfuSe2CVQtf23Fs2yK+fVcagQCE5LTITcj0YY8t1b69mLTLKwd+670kQr67MHYOrr4v0PSA8LX881c3jL+hlJm3xDpTSKp9tVm6eEEjB5H1O3trjVHxOodSAZwXWmo2sh7FQsLEtmF+R9C14eF2a0YyRC33hcxPsCJGPRITl2mZT6kz4AcYlykSzQTL81rzfY/YWCQev6ozZK4jxWnHoXzfyDC8TKVd5ocfSE1XkKwuYbpPnSnab3urZivtSeMYrDmVOUKAH6l4iwpFbZbVGIA4uHH3floArMXXqVGfFfHUVBmiACeWMS6oH2io7TzFaKEaaqUDYpgNH7XNwlIPurxPaQSsedrTtAOKoo/uuzgGQ==
    LD_SUPERUSER_PASSWORD: AgBRtxURW4dZHtpBIKDeoYs7thNnT7OHCXfHFVrgfCkkOehMuq24c+XKIf0nI/z4+G5ygLcBC2NSovrpYjyAr00ZhbiM/Ln54uNZEMMxkXM8XjqPI+GOYy1SDFRFAHkmn/PGRQCYIn6CHFxe1xugOrqXfrpHfPenM611cf6GpQuJhLQteKY1JHav0rUFkk4F+WGkeJ5hiGjZXi6pkEroCsEEh7eeUJFO9SfEbWKwZHF1eCEvjlts34JQr5R9iFJBLRiq5i8HX1E3H1mu1uRDVjFdrcJ+W1PmjwmxakxrR2WqmF6F35f0/m3talgxyPWeVmUgmKTPaj7j1A+nRs/m3kLdlmFfBkfNdEXQhjQm4W834aLPclZw3Q+B69W3ijop/VTP2gHmg41mpGpbPxqM7Yc9b6IIDjTTE+PEMWctVhvrv7g4//9ap+4fHu17EgmjKrlyrEJC0tbUQHAtf5ZpIG8oXhRRbqKc5ssGAwdK+HYDB30MoXYCqsUMr+C1+v0nTSGGUW7LIpXkr1uwalQs2lFhWeGW7Eu/udb7f1nMp9305gxV0mBow4t/GV425+xXU27J78Y8EPn0b2kqZfcbS68B8ZIz5vo23H4GsadGW1VWjWrAjuxkUUSOR1+nyoaUMui4nktDZILs5l7L4Zt2+YGI/mXSHL55WQyNwO86Qs1BdAvEJnl/9s1rGOJ6ewYGsLmk8xeOzDC8lTPPwZ0xbCHuM/75JOwse35kRIk=
  template:
    metadata:
      name: linkding-secrets
      namespace: linkding
    type: Opaque
