---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secrets
  namespace: paperless-ngx
spec:
  encryptedData:
    secret-key: AgBoOjwvBm6AQ7L8TzT74lVgHBoISlJFMCtqaZzepGj6/9+k6JBjm8TKh1EoXduud92KwNgmEsOApiW52ue7GlRWmWFKCOOauEHo/8wloyLJq4emIgJso5wEi1xQDI765P8wKgeNOa3kPazTboxQpluFoT4ZkDxZ8jnytJjd8SpvdH2/E5oyU5jutaRKkXeC4GPauz0sdviqhE+ZYTVqKbmUZt01Dow8A16mPBTh+23fQuzSCXUyO+iudaXBfam+O/h5tkmSt8p46aZVICeGENMFaaHHLq5tY1S5P6k8wc9F70H+Lsn3Yjv18WQkJRLLox5cg2ftcYfSLn4zVLYHG4JsEdju6PGEd327wImsPfn7HqUhGzLdrRGdziDxBOAwzSQXT3upKqazjwSCvPdIm8r+Cr9zlUx8UC3NdMHrcc4JBKyPicV0B9m6Iyt4Lw7l3rbSw9VpPCIj7PyiIj2qDL/jNlm/NbrBwqlJn+wfqywzUt9yx2z5cmAHWGyVRKtmZj48jPWOaFyYhvp9kc2BBpzfqey6ugHtP7Hyr30BB0aXUI6lQqo9TgPVvS96cCjKlGYSLLuMxW//zppZ8dlUPQYS5MysFXlex6bQN50YFJffJ2LiKc1Xcak5qyi6gUTA/Evv03fnL9U3Xvx7V0MrHonFRZzbl3toxnRXpZRck8tAq2kYbxbJn4+iWJa/A1FhKaNmYCZGm5DVa+XlzmO9jwcHu5K1nedFePHqsHYoc4ZtQuiM9SWmj0tG1r1TTEHqVV10oAE4m9HZ8vUkwB7eZRjfDmPGlnCvCclO4n9Zya/sLINxa0Vqb2DS
  template:
    metadata:
      name: paperless-secrets
      namespace: paperless-ngx
