apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
  labels:
    app: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - image: ghcr.io/kareadita/kavita:latest
          name: kavita
          ports:
            - containerPort: 5000
          env:
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: kavita-data
              subPath: manga
              mountPath: /manga
            - name: kavita-data
              subPath: comics
              mountPath: /comics
            - name: kavita-data
              subPath: books
              mountPath: /books
            - name: kavita-data
              subPath: config
              mountPath: /kavita/config
      volumes:
        - name: kavita-data
          persistentVolumeClaim:
            claimName: kavita-data
      
