apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kavita
  namespace: kavita
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bib.mauzlab.de`)
      services:
        - name: kavita
          port: 5000