apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-data
  namespace: kavita
spec:
  storageClassName: nfs-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    