apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
namespace: sealed-secrets

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.33.1/controller.yaml

# Disable automatic key rotation
patches:
  - target:
      kind: Deployment
      name: sealed-secrets-controller
      namespace: kube-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--key-renew-period=0"